-- Indoscientist Supabase schema
-- Jalankan di Supabase SQL Editor.

create table if not exists public.materi (
  id bigint generated by default as identity primary key,
  judul text not null,
  mapel text not null check (mapel in ('matematika','fisika','kimia','biologi')),
  kelas text not null,
  deskripsi text,
  link_file text,
  created_at timestamptz default now()
);

create table if not exists public.bank_soal (
  id bigint generated by default as identity primary key,
  judul text not null,
  mapel text not null check (mapel in ('matematika','fisika','kimia','biologi')),
  kelas text not null,
  deskripsi text,
  link_file text,
  created_at timestamptz default now()
);

create table if not exists public.artikel (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text default 'pendidikan',
  ringkasan text,
  isi text,
  created_at timestamptz default now()
);

alter table public.materi enable row level security;
alter table public.bank_soal enable row level security;
alter table public.artikel enable row level security;

-- Semua pengunjung boleh membaca konten.
drop policy if exists "public read materi" on public.materi;
create policy "public read materi" on public.materi for select using (true);

drop policy if exists "public read bank soal" on public.bank_soal;
create policy "public read bank soal" on public.bank_soal for select using (true);

drop policy if exists "public read artikel" on public.artikel;
create policy "public read artikel" on public.artikel for select using (true);

-- Hanya user yang login boleh menambah/mengubah/menghapus konten.
drop policy if exists "authenticated insert materi" on public.materi;
create policy "authenticated insert materi" on public.materi for insert to authenticated with check (true);
drop policy if exists "authenticated update materi" on public.materi;
create policy "authenticated update materi" on public.materi for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete materi" on public.materi;
create policy "authenticated delete materi" on public.materi for delete to authenticated using (true);

drop policy if exists "authenticated insert bank soal" on public.bank_soal;
create policy "authenticated insert bank soal" on public.bank_soal for insert to authenticated with check (true);
drop policy if exists "authenticated update bank soal" on public.bank_soal;
create policy "authenticated update bank soal" on public.bank_soal for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete bank soal" on public.bank_soal;
create policy "authenticated delete bank soal" on public.bank_soal for delete to authenticated using (true);

drop policy if exists "authenticated insert artikel" on public.artikel;
create policy "authenticated insert artikel" on public.artikel for insert to authenticated with check (true);
drop policy if exists "authenticated update artikel" on public.artikel;
create policy "authenticated update artikel" on public.artikel for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete artikel" on public.artikel;
create policy "authenticated delete artikel" on public.artikel for delete to authenticated using (true);

insert into public.materi (judul, mapel, kelas, deskripsi, link_file) values
('Persamaan Linear', 'matematika', 'X', 'Konsep variabel, koefisien, konstanta, dan penyelesaian persamaan.', '#'),
('Fungsi Kuadrat', 'matematika', 'X', 'Grafik parabola, akar-akar, titik puncak, dan aplikasi soal.', '#'),
('Besaran dan Satuan', 'fisika', 'X', 'Besaran pokok, turunan, satuan SI, dan angka penting.', '#'),
('Struktur Atom', 'kimia', 'X', 'Proton, neutron, elektron, isotop, dan konfigurasi elektron.', '#'),
('Sel Kehidupan', 'biologi', 'X', 'Organel sel, membran, inti sel, serta sel hewan dan tumbuhan.', '#')
on conflict do nothing;

insert into public.bank_soal (judul, mapel, kelas, deskripsi, link_file) values
('Soal Persamaan Linear', 'matematika', 'X', '20 soal pilihan ganda dan 5 soal uraian.', '#'),
('Soal Gerak Lurus', 'fisika', 'X', 'Latihan GLB, GLBB, grafik, kecepatan, dan percepatan.', '#'),
('Soal Struktur Atom', 'kimia', 'X', 'Latihan nomor atom, nomor massa, dan konfigurasi elektron.', '#')
on conflict do nothing;

insert into public.artikel (judul, kategori, ringkasan, isi) values
('5 Cara Belajar Matematika Agar Tidak Sulit', 'matematika', 'Tips sederhana agar konsep matematika lebih mudah dipahami.', 'Mulailah dari konsep dasar, kerjakan contoh soal, lalu latihan bertahap.'),
('Mengapa Fisika Penting dalam Kehidupan?', 'fisika', 'Fisika hadir dalam teknologi dan aktivitas sehari-hari.', 'Fisika membantu kita memahami gerak, energi, listrik, dan teknologi modern.')
on conflict do nothing;
